### ISSUE TITLE
Documentation is nonexistant

### ISSUE THREAD

**Issue by seisvelas** [openneo/neopia#2]
I'd love to use a Neopets API. Is this repo what I'm looking for? Unknowable because sadly, there isn't even a readme!

**Comment by Zei33** [comment]
I can't figure it out. I got the program running but I need a bit more detail on how to make requests. Even a few example requests would be enough to get me started. Totally lost.

**Comment by matchu** [comment]
Ehe, tbqh, this is yet another project where we had Amibitious Goals of "wow we can make this an API for so many things"… then we eventually dramatically cut scope and was like "fiiine, I guess this will just be a gateway for exactly the customization pieces that Dress to Impress needs".

I'm guessing it's probably not actually what you're looking for 😓 I'll tweak the desc & readme a bit to reflect this. Sorry & thanks for the ping!
